# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site language
lang: en-US

# Site title
title: "Warren Gates"

# A description of your site for meta tag, search engine results.
description: "Software Engineer"

# The subpath of your site, e.g. /blog, for generating urls.
baseurl: ""

# The base hostname & protocol of your site for where absolute urls are needed.
url: "https://warrengates.dev"

# Favicon
# favicon.io, font=bilbo, bgcolor=#5885af, font color=#ffffff
favicon: images/favicon.png

# Site navigation - each item must have a title and a url.
navigation:
  - text: Home
    url: /
  - text: Projects
    url: /projects/
  - text: Resume
    url: /resume/
  - text: About
    url: /about/

accent_color: '#5885AF'

# Site footer
footer:
  content: <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/80x15.png" /></a><br /><span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">warrengates.dev</span> by <a xmlns:cc="http://creativecommons.org/ns#" href="https://warrengates.dev" property="cc:attributionName" rel="cc:attributionURL">Warren Gates</a> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.
  has_social: true

# Plugins
plugins:
  - jekyll-paginate

# http://jekyllrb.com/docs/pagination/
paginate: 3
paginate_path: '/page:num/'


# Permalinks
permalink: pretty

# Conversion
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude:
  - README.md
  - LICENSE.md
  - notes.md

# https://github.com/penibelst/jekyll-compress-html
compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []